tqec/tqec

- tqecjs/README.md
- tqecjs/src/App.js
- tqecjs/src/workspace/QubitClass.js
- tqecjs/src/workspace/components/button.js
- tqecjs/src/workspace/components/notifier.js
- tqecjs/src/workspace/plaquettes/PlaquetteClass.js
Per my comment #13, that plaquettes cannot be copied. Adding in interactivity.
Adding additional minor improvements, particularly around colors.
> Make plaquettes interactive, minor cleanups

- check/all_.py
- check/coverage_.py
- check/flake8_.py
- check/format_.py
- check/mypy_.py
- check/pylint_.py
- check/pytest_.py
- check/requirements.py
> Delete check directory

- notebooks/corner.ipynb
- notebooks/doubling_distance.ipynb
- src/tqec/templates/base.py
- src/tqec/templates/orchestrator.py
- src/tqec/templates/scalable/rectangle.py
- src/tqec/templates/scalable/square.py
Closes #36 
Now the scaling factor `k` is defined as the half actual dimension/size of the scalable template axis. And all the `k` in the notebooks are halved as well.
> Change the definition of scaling factor k

- tqecjs/src/workspace/QubitClass.js
closes: #27
Am I missing something, or is this all that was needed?
> Remove qubit if it already exists

- frontend/.eslintrc.json
Updated eslint, relaxed rules for indentation, tabs, and react. We can enforce them later
> update eslint, allow tabs

- src/tqec/plaquette/schedule.py
- src/tqec/templates/orchestrator.py
- src/tqec/templates/scalable/rectangle.py
> Fix a few regressions introduced in a previous commit

- src/tqec/__init__.py
- src/tqec/templates/__init__.py
- src/tqec/templates/atomic/__init__.py
- src/tqec/templates/atomic/square.py
- src/tqec/templates/constructions/__init__.py
This PR fixes a few issues in the `AlternatingCornerSquareTemplate` class. 
Fix #154
> Fix `AlternatingCornerSquareTemplate`

- ruff.toml
> Fix linter warnings F401

- frontend/src/plaquettes/CircuitWriter.js
This is a very small change that will make sure npm run start will run.
> fix documentation lint issue

- src/tqec/plaquette/library/utils/pauli.py
> Tag Pauli memory syndrome qubit as mergeable

- .github/FUNDING.yml
There can be up to 4 sponsored usernames here. Right now, it's only me, but it needs to be in list format.
> Fix list syntax

- frontend/package-lock.json
- frontend/package.json
> Add cypress to the frontend

- src/tqec/circuit/operations/measurement_map.py
> Fix typing issue in CircuitMeasurementMap

- frontend/package-lock.json
- frontend/src/actions.js
- frontend/src/components/notification.js
- frontend/src/control-flow.js
- frontend/src/graphics/Grid.js
- frontend/src/plaquettes/Plaquette.js
- frontend/src/qubits/Qubit.js
- frontend/src/qubits/QubitLabels.js
- frontend/src/qubits/QubitLattice.js
- frontend/src/reducers.js
Implement issue #219. Redesign from the revised task flow, task 2.
* Retain the footprint after specifying it, along with the lattice of qubits.
* When I specify the qubit constellation against the footprint, ensure that if the footprint were to be copied over, there would be no overlapping qubits.
* Revised qubit population technique
* Cycle through X and Z, and specify a time stamp.
> [Rev. Task 2-5] Plaquette specification

- requirements.txt
- src/tqec/sketchup/__init__.py
- src/tqec/sketchup/dae_parse.py
- src/tqec/sketchup/dae_parse_test.py
- src/tqec/sketchup/dae_parse_test/cnot.dae
- src/tqec/sketchup/dae_parse_test/templates.dae
A direct port of C++ parse script like #252  does work but using the existing COLLADA parsing library like `pycollada` seems more robust and performant.
> Implement SketchUp-exported dae file parsing with `pycollada`

- src/tqec/templates/constructions/grid_test.py
- src/tqec/templates/constructions/qubit.py
This fixes the last merge that has been performed too quickly.
> Fix grid.py and grid_test.py

- README.md
- pyproject.toml
- requirements-dev.txt
This PR fixes #311 by adding installation instructions and linking to the issue if users encounter this particular problem.
> Update installation instructions in README

- src/tqec/circuit/operations/operation.py
This should fix the issue raised in #297. I could not test the fix, so not merging for the moment. 
Maybe @Gistbatch you can try on the specific file you mentioned?
> Fix the translation to stim issue

- src/tqec/templates/subtemplates.py
CI on windows failed after the [last commit](https://github.com/QCHackers/tqec/actions/runs/11117093969/job/30888466220#step:8:18) due to incompatible numpy types. This PR includes the fix to the mypy error.
> Fix mypy error on windows

- docs/quick_start.rst
- src/tqec/_cli/subcommands/run_example.py
- src/tqec/_cli/tqec.py
Closes: #369, #366
I've extended the cli and the *getting started* docs.
I wasn't sure how much I should include, let me know what you think
> Improve getting started 

- docs/user_guide/quick_start.rst
- docs/user_guide/terminology.rst
**Overview**
Fixed minor typos while exploring the docs.
> Fix NoiseModel import in qick_start.rst

- pyproject.toml
- requirements-dev.txt
- requirements.txt
- src/tqec/computation/_base_graph.py
- src/tqec/computation/block_graph.py
- src/tqec/computation/conversion_test.py
- src/tqec/computation/zx_graph.py
- src/tqec/computation/zx_graph_test.py
- src/tqec/gallery/__init__.py
- src/tqec/gallery/logical_cnot_test.py
- src/tqec/gallery/logical_cz.py
- src/tqec/gallery/logical_cz_test.py
This PR adds logical CZ gates to the gallery and implements methods for rotating the `ZXGraph` and `BlockGraph` by multiples of 90 degrees.
> Add logical CZ gate to gallery

- src/tqec/compile/observables/abstract_observable.py
- src/tqec/compile/observables/abstract_observable_test.py
- src/tqec/gallery/__init__.py
- src/tqec/gallery/move_rotation.py
- src/tqec/gallery/move_rotation_test.py
- src/tqec/gallery/solo_node.py
- src/tqec/gallery/solo_node_test.py
This PR adds move rotation and stability experiment factory functions to gallery.
Move Rotation:
Stability:
> More gallery computations

- src/tqec/__init__.py
- src/tqec/circuit/generation.py
- src/tqec/circuit/measurement.py
- src/tqec/circuit/measurement_test.py
- src/tqec/circuit/qubit.py
- src/tqec/circuit/qubit_test.py
- src/tqec/compile/block.py
- src/tqec/compile/compile.py
- src/tqec/compile/detectors/compute.py
- src/tqec/compile/detectors/compute_test.py
- src/tqec/compile/detectors/database.py
- src/tqec/compile/observables/builder_test.py
- src/tqec/plaquette/plaquette.py
- src/tqec/position.py
- src/tqec/position_test.py
- src/tqec/templates/indices/_testing.py
- src/tqec/templates/indices/base.py
- src/tqec/templates/indices/layout.py
- src/tqec/templates/indices/subtemplates_test.py
- src/tqec/templates/rpng.py
> Enforce coordinate system for `Position2D`

- docs/user_guide/index.rst
Related to #471 
There should be 3 files listed under `Tutorials`. 
| Before      | After |
| :---        |    :----:   |  
|![image](https://github.com/user-attachments/assets/38ff3e95-63b1-488c-8142-60e98389fe40)| ![image](https://github.com/user-attachments/assets/279dba86-b4ce-4996-b4fc-eea983120a75)|
> Ensure file is listed correctly in the user guide

- src/tqec/compile/compile.py
- src/tqec/compile/compile_test.py
- src/tqec/computation/block_graph.py
- src/tqec/computation/block_graph_test.py
Fix https://github.com/tqec/tqec/issues/458#issuecomment-2656115898.
> Shift correlation surface during compilation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/finding_materials_from_recordings.md
> Better issue templates

- src/tqec/compile/detectors/compute.py
- src/tqec/compile/generation.py
- src/tqec/compile/tree/annotators/polygons.py
- src/tqec/templates/subtemplates.py
- src/tqec/templates/subtemplates_test.py
- src/tqec/utils/rotations.py
This PR fixes a few errors that started to appear recently due to an update. See [this comment](https://github.com/tqec/tqec/pull/562#issuecomment-2858674191) for more information.
> Fix new errors reported by `mypy` after update

- docs/conf.py
> Update copyright year in docs
