tqec/tqec

- notebooks/doubling_distance.ipynb
- src/tqec/constructions/corner.py
- src/tqec/constructions/qubit.py
- src/tqec/templates/scalable/rectangle.py
Close #63
Now the `ScalableRectangle` accepts `scale_width` to specify whether to scale the width or height, which will be set to the dimension with larger even value when not specified.
> Fix the rectangle scaling problem

- src/tqec/display.py
Currently we only have `display_template` to view a `TemplateOrchestrator` as ASCII texts. It is hard to tell the boundaries between the templates from the raw texts.
I add a simple implementation of `display_templates_svg` to get a svg view for the `TemplateOrchestrator`. The implementation is not carefully designed and use several private methods of `TemplateOrchestrator`, which definitely needs to be refactored in the future. However, I think it is ok to use it during development for debugging.
The code demo is as below:
```python
from tqec.constructions.corner import ScalableCorner
from tqec.display import display_templates_svg
corner = ScalableCorner(3)
display_templates_svg(corner, "corner.svg")
```
Here are the svg views for the examples in …
> Add function to display a `TemplateOrchestrator` as a svg file

- src/tqec/detectors/measurement_map.py
- src/tqec/detectors/operation.py
- src/tqec/detectors/transformer.py
- src/tqec/display.py
- src/tqec/generation/circuit.py
- src/tqec/generation/topology.py
- src/tqec/noise_models/after_clifford_depolarization.py
- src/tqec/noise_models/after_reset_flip.py
- src/tqec/noise_models/base.py
- src/tqec/noise_models/before_measure_flip.py
- src/tqec/noise_models/before_round_data_depolarization.py
- src/tqec/noise_models/idle_qubits.py
- src/tqec/noise_models/multi_qubit_gates.py
- src/tqec/non_template_scaling/display_data.py
- src/tqec/plaquette/plaquette.py
- src/tqec/plaquette/schedule.py
- src/tqec/templates/base.py
- src/tqec/templates/composed.py
- src/tqec/templates/constructions/corner.py
- src/tqec/templates/constructions/qubit.py
- src/tqec/templates/fixed/base.py
- src/tqec/templates/scalable/rectangle.py
- src/tqec/templates/shapes/base.py
- src/tqec/templates/shapes/rectangle.py
- src/tqec/templates/shapes/square.py
Closes #118 
This PR changes the docstring style of all the functions and classes from rest to google style.
Initially, I used [pyment](https://github.com/dadadel/pyment) for this, however, it turns out `pyment` cannot handle the multi-line argument descriptions correctly[^1]. Then I turn to a less well-known package [docconvert](https://github.com/cbillingham/docconvert) and it worked out quite well.
I have checked the auto-converted files with `diff` preview in my IDE, but slight errors might still exist. The conversion process can be reproduced following the procedure below:
1. Install the `docconvert` python package: 
```shell
pip install docconvert
```
2. Create the configuration file `docconvert.json` under the directory of your `tqec` project:
```json
{
"input_style": "rest", …
```
> Change the docstring style to Google style

- src/tqec/detectors/measurement_map.py
- src/tqec/detectors/operation.py
- src/tqec/exceptions.py
- src/tqec/generation/circuit.py
- src/tqec/plaquette/plaquette.py
- src/tqec/plaquette/schedule.py
I noticed several exception types in the docstring that weren't updated properly after the merge of #73. This pull request primarily addresses those types. Additionally, I identified one argument docstring that wasn't properly converted in #112, and I fixed that as well.
> Fix some exception types in docstring

- src/tqec/detectors/measurement_map.py
- src/tqec/detectors/operation.py
- src/tqec/detectors/transformer.py
- src/tqec/display.py
- src/tqec/generation/circuit.py
- src/tqec/plaquette/plaquette.py
- src/tqec/plaquette/schedule.py
- src/tqec/templates/base.py
- src/tqec/templates/constructions/qubit.py
- src/tqec/templates/scalable/rectangle.py
This PR adds support for Python 3.9, mostly by adding `from __future__ import annotations` at the top of files that are using [PEP 604](https://peps.python.org/pep-0604/).
Fixes #123.
> Add support for Python 3.9

- src/tqec/detectors/measurement_map.py
The `CircuitMeasurementMap.get_measurement_relative_offset` was documented to return `None` when the measurement was not found, but raised in the case of a measurement not found because there was none. This is fixed by returning `None` instead of raising.
> Fix CircuitMeasurementMap not adhering to the documented API

- notebooks/corner.ipynb
- notebooks/doubling_distance.ipynb
- notebooks/logical_qubit_extended_memory_experiment.ipynb
- notebooks/logical_qubit_memory_experiment.ipynb
- notebooks/move_qubit_along_a_line.ipynb
- src/tqec/__init__.py
- src/tqec/circuit/__init__.py
- src/tqec/plaquette/__init__.py
- src/tqec/plaquette/library/empty.py
- src/tqec/plaquette/library/initialisation.py
- src/tqec/plaquette/library/measurement.py
- src/tqec/plaquette/library/xx.py
- src/tqec/plaquette/library/xxxx.py
- src/tqec/plaquette/library/zz.py
- src/tqec/plaquette/library/zzzz.py
- src/tqec/plaquette/plaquette.py
- src/tqec/plaquette/qubit.py
This PR decouples the `Plaquette` classes from their `qubits`, removing `SquarePlaquette` and `RoundedPlaquette` and allowing the description of higher-level plaquettes with less code duplication.
Fixes #172
> Decouple Plaquette and qubits

- src/tqec/templates/base.py
I do not see a better way of checking the number of plaquettes provided to the `instantiate` method. This PR adds documentation to `Template._check_plaquette_number` to explicitly provide guidance on how to use that method.
Fixes #197
> Improve plaquette number checking

- README.md
- pyproject.toml
This PR adds the newly functional link to the sphinx-generated documentation to:
- the `README.md` file.
- the `pyproject.toml` file, under the name "Documentation"
Fixes #221.
~~It might close (decided that it will not for the moment) #109, but #109 contains a list of points that should be done, and that are not fully done yet.~~
> Add GitHub Pages link to documentation

- src/tqec/templates/constructions/grid.py
- src/tqec/templates/constructions/grid_test.py
- src/tqec/templates/constructions/qubit.py
This PR implements a generic `TemplateGrid` that can be used to generate a grid of templates representing logical qubits (for example).
Closes #244
> Implement `TemplateGrid`

- src/tqec/templates/constructions/qubit.py
Fix #282 by implementing two new templates representing 2 qubit borders glued together.
> Implement qubit borders template

- src/tqec/sketchup/block_graph.py
- src/tqec/sketchup/block_graph_test.py
Fix #304 and #308.
When the `ZXGraph` has no corner, the non-virtual node with minimum position will be chosen and the orientation will be selected. The X axis will be intended to align across the spatial X boundares of the cube if possible.
> Choose orientation for simple `ZXGraph` when converting to `BlockGraph`

- .github/workflows/ci.yml
- .github/workflows/exotic-oses.yml
- .github/workflows/gh-pages.yml
- src/tqec/sketchup/collada_test.py
This PR includes installation / test / type analysis on both Windows and MacOS. Because these are more costly than Linux (resp. x2 and x10), I tried to make the workflow run only when everything else succeeded.
Closes #311
> Add CI run on Microsoft / MacOS 

- src/tqec/templates/display.py
This commit fixes an off-by-1 error in an indexing. 
The `plaquette_indices` tuple does **NOT** include the `0` plaquette, so the index should be decreased by 1.
> Fix off-by-1 error in Template display

- .github/FUNDING.yml
Sam has been away for a long time and his front-end development is now stale and has been removed from the `main` branch (but still backed up by #326 in https://github.com/QCHackers/tqec/tree/backup/frontend_v1). There is no meaning to have him in the FUNDING.yml file anymore. As with #326, this change might be reverted if work on the front-end is resumed.
> Removing FUNDING.yml file

- examples/benchmarks/bench.sh
- examples/benchmarks/cnot_all_observables.py
- pyproject.toml
This PR fixes #328 by adding a few files to benchmark the runtime of the `tqec` library to generate a fully annotated (detectors and observables) `stim` file from a `.dae` file and a scaling factor `k`.
To start a benchmark:
```bash
cd examples/benchmarks/
./bench.sh cnot_all_observables.py 2
```
This should output something along the lines of
```
Saving all benchmark data to data/cnot_all_observables_k=2_2024-10-03_13-02-42
Statistical profiling of cnot_all_observables.py using pyinstrument...
Profiling saved as an HTML webpage in data/cnot_all_observables_k=2_2024-10-03_13-02-42/cnot_all_observables_k=2.html
```
and you will be able to open the benchmark data by opening the static and self-contained HTML file generated.
> Adding benchmarks using topological CNOT generation

- src/tqec/circuit/generation.py
- src/tqec/circuit/generation_test.py
- src/tqec/circuit/observable_qubits.py
- src/tqec/circuit/observable_qubits_test.py
- src/tqec/compile/block.py
- src/tqec/compile/compile.py
- src/tqec/compile/observables.py
- src/tqec/templates/_testing.py
- src/tqec/templates/_testing_test.py
- src/tqec/templates/base.py
- src/tqec/templates/display.py
- src/tqec/templates/layout.py
- src/tqec/templates/qubit.py
- src/tqec/templates/qubit_test.py
Managing the scaling parameter `k` in `Template` instances is not needed at all, in fact `k` can just be provided to the functions that need it.
This is less error-prone as we do not have to manage scaling parameters that should be kept in-sync.
> Avoid storing `k` in `Template` instances

- pyproject.toml
- requirements.txt
Fix #363 
From @nelimee:
> - When trying to install tqec, I had an issue due to Python 3.13 being the newest Python version but most of our dependencies (and in particular stim) do not have yet pre-built binaries, leading to some issues related to CPython imports in stim.
> 
> - The `typing-extensions` package seems to be missing from our requirements. I though it was a standard python package, it seems like this is not the case.
> Require `python<3.13` and add `typing-extensions` to requirements

- src/tqec/plaquette/library/css.py
- src/tqec/plaquette/library/css_test.py
- src/tqec/plaquette/library/empty.py
- src/tqec/plaquette/library/zxxz.py
- src/tqec/plaquette/library/zxxz_test.py
- src/tqec/plaquette/plaquette.py
This PR adds a descriptive `name` field to each `Plaquette` instance. Because `Plaquette` instances are frozen, it also uses this unique name to implement `__eq__` and `__hash__`. Finally, it uses the name to represent a plaquette with `__str__`.
Fixes #360.
> Add name to `Plaquette`

- src/tqec/compile/detectors/database.py
- src/tqec/compile/detectors/database_test.py
- src/tqec/plaquette/frozendefaultdict.py
- src/tqec/plaquette/plaquette.py
This PR fixes #374 and refactor a little bit `DetectorDatabase` and its accompanying key data-structure `_DetectorDatabaseKey` to:
1. be translation free, meaning that now equivalent pairs of subtemplates/plaquettes are mapped to the same database entry.
2. use a simpler hashing method that is fully contained in the `database.py` (and not spread in the different data-structures used) and only require that `Plaquette.name` is a valid way of comparing/hashing plaquettes (i.e., the following assertion should hold: "two plaquettes have the same name iff they are equal").
> `DetectorDatabase` is now implemented with a translation-invariant key system

- .pre-commit-config.yaml
- src/tqec/circuit/schedule/__init__.py
- src/tqec/circuit/schedule/circuit.py
- src/tqec/circuit/schedule/circuit_test.py
- src/tqec/circuit/schedule/exception.py
- src/tqec/circuit/schedule/manipulation.py
- src/tqec/circuit/schedule/manipulation_test.py
- src/tqec/circuit/schedule/schedule.py
- src/tqec/circuit/schedule/schedule_test.py
This PR fixes #358.
The first commit of this PR splits `src/tqec/circuit/schedule.py` into multiple files in the newly created folder `src/tqec/circuit/schedule/` and re-export all the public symbols in its `__init__.py`.
The subsequent commits will likely implement a `FrozenScheduledCircuit` data structure.
> Refactor `tqec.circuit.schedule` into submodules

- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
There are currently two actions in the CI that require write permission to the repository in order to work correctly: 
- `Add Coverage PR Comment`: Adds code coverage report to PR.
- `Deploy if PR`: Adds documentation generation to PR.
The issue has been reported in #401 .
Changing the permissions for external PRs could be a security issue, therefore silent failure was chosen as the preferred method.
This PR adds [ `continue-on-error` ](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) to allow for step failure, and makes the step `Add comment if PR` dependent on success of `Deploy if PR`.
> Allow CI/CD to fail for external PRs without required permissions

- docs/user_guide/build_computations.ipynb
The documentation should explicitly say that SketchUp usage is OS dependent, to avoid confusing first time users. I clarify this portion of the docs in this short PR.
> clarified sketch-up os dependency

- src/tqec/__init__.py
- src/tqec/compile/__init__.py
- src/tqec/simulation/__init__.py
Small PR to address issue #418. I was exploring #364 and noticed some functions in the `simulation` module were not in the API documentation either, so I update the init file similarly.
> Ensuring `simulation` and `CompiledGraph` appear in API docs

- docs/contributor_guide.rst
After #390, the [user guide](https://tqec.github.io/tqec/contributor_guide.html#create-a-specific-branch-for-each-issue) still mentions `QCHacker/tqec repository` for creating branches and forked branches. This PR corrects this. 
Some typos on the contributing page were also corrected.
> Update contributing guide in docs

- src/tqec/computation/correlation.py
- src/tqec/computation/correlation_test.py
Resolves https://github.com/tqec/tqec/issues/441.
I added a test which is sensitive to this bug. Thereby I also refactored the (test) code a little bit. 
I solved the bug by initializing the frontier with a fresh instantiation of the leaf without the label. This solution fits best with the rest of the code because this is actually done too when adding new nodes to the frontier. It also makes sense in regard of the fact that the span just reuses `ZXNode` in a way where a label has actually no meaning.
> Fix duplicate correlation surfaces

- docs/conf.py
- examples/notebooks/sketchup_model.ipynb
- pyproject.toml
This PR adds `sphinx_copybutton` as a dependency. Due to this, the code blocks in the documentation can be easily copied (as required).
To see the `copy` option, hover over the top right corner of a code block in the docs.
https://sphinx-copybutton.readthedocs.io/en/latest/
> Allow the option to copy code blocks in the documentation

- README.md
- docs/user_guide/quick_start.rst
- src/tqec/compile/specs/base.py
1. Fix https://github.com/tqec/tqec/issues/479
As suggested by @inmzhang, move rotation structure includes spatial cube and is not supported by the compilation yet.
Now when trying compile `move_rotation`, the output is 
```
Traceback (most recent call last):
File "/home/zhaoyilun/workspace/github/quantum-computing-resources/learning/qec/tqec_learn/test_move_rotation.py", line 8, in <module>
compiled_computation = compile_block_graph(block_graph, observables="auto")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/zhaoyilun/workspace/github/forks/tqec/src/tqec/compile/compile.py", line 350, in compile_block_graph
blocks[cube.position] = block_builder(spec)
^^^^^^^^^^^^^^^^^^^
File "/home/zhaoyilun/workspace/github/forks/tqec/src/tqec/compile/specs/library/_utils.py", line …
```
> fix: close #479

- src/tqec/computation/block_graph.py
- src/tqec/computation/block_graph_test.py
- src/tqec/gallery/cz.py
- src/tqec/interop/collada/read_write_test.py
- src/tqec/utils/rotations.py
- src/tqec/utils/rotations_test.py
With #468, we can now import a `.dae` file with rotation transformations as a `BlockGraph`. This PR introduces direct rotation functionality to the `BlockGraph` data structure, allowing us to rotate by multiples of 90 degrees using `block_graph.rotate`.
> Implement `rotate` method on block graph

- docs/Makefile
- docs/contributor_guide.rst
- docs/user_guide/terminology.rst
Fixes #496
I did not need to add `rm _autosummary/*` to the makefile because switching to a Python 3.12 environment fixed the duplicate target issues.
> Fix docs build errors and update contributing guide

- src/tqec/computation/block_graph.py
- src/tqec/computation/cube.py
- src/tqec/interop/collada/read_write.py
- src/tqec/interop/collada/read_write_test.py
Fixes https://github.com/tqec/tqec/pull/510#issuecomment-272544649.
In the following `.dae` file, the highlighted cube is incorrectly defined as `ZZX` instead of `ZXZ`. Although it appears correct because its front and back faces are shadowed by connected pipes, this discrepancy can affect cube kinds and the compilation pipeline.
This PR introduces a new method, `fix_shadowed_faces`, in `BlockGraph` to detect and correct such shadowed faces by adjusting their basis to match the pipe color. For example, the cube above will be properly corrected to `ZXZ`. The fix procedure has also been integrated into `BlockGraph.from_dae_file`, allowing users to make such fixable mistakes in SketchUp without affecting the final compilation.
> Fix shadowed faces to match pipe color

- src/tqec/computation/block_graph.py
Look for a cube using its label #517
get_cubes_by_label(label): With a given str, the label, returns the 3D integer position, and the CubeKind (ZXCube | Port | YHalfCube)
I checked using this:
```
result = block_graph.get_cubes_by_label("P3")
if result:
position, kind = result
print(f"Cube found at {position} with kind {kind}")
else:
print("No cube found with that label")
```
Result:
```
python cubes_label_test.py
Cube found at (-1,0,3) with kind PORT
```
> Get cubes by label

- src/tqec/circuit/moment.py
- src/tqec/post_processing/merge.py
- src/tqec/post_processing/merge_test.py
- src/tqec/post_processing/remove.py
- src/tqec/post_processing/remove_test.py
- src/tqec/post_processing/utils/moment.py
This PR implements two post-processing functions for `stim.Circuit`:
- `remove_empty_moments`
- `merge_adjacent_moments`
The implementation of `merge_adjacent_moments` should fix #462.
> Implement a few post-processing functions for `stim.Circuit`

- src/tqec/compile/block.py
- src/tqec/compile/blocks/block_test.py
- src/tqec/compile/blocks/layers/atomic/layout_test.py
- src/tqec/compile/blocks/layers/atomic/plaquettes_test.py
- src/tqec/compile/blocks/layers/composed/repeated_test.py
- src/tqec/compile/blocks/layers/composed/sequenced_test.py
- src/tqec/compile/blocks/layers/merge_test.py
- src/tqec/compile/detectors/compute_test.py
- src/tqec/compile/generation_test.py
- src/tqec/compile/specs/library/_utils.py
- src/tqec/compile/specs/library/generators/hadamard.py
- src/tqec/compile/specs/library/generators/memory.py
- src/tqec/compile/specs/library/generators/spatial.py
- src/tqec/compile/tree/annotators/detectors_test.py
- src/tqec/compile/tree/node_test.py
- src/tqec/plaquette/plaquette.py
- src/tqec/templates/layout.py
- src/tqec/utils/frozendefaultdict.py
As described in #534, using `default_factory` makes it tricky to check whether to `Plaquettes` instances have the same way generating default plaquette. 
https://github.com/tqec/tqec/blob/f8ebe11d68eda66345568cf48a8e14f8a59686fb/src/tqec/templates/layout.py#L209-L219
As suggested by @nelimee, it's better to use `default_value`.
Now this program run without error
<details><summary> program </summary>
```python
from tqec.compile.blocks.block import Block
from tqec.compile.blocks.layers.atomic.plaquettes import PlaquetteLayer
from tqec.compile.blocks.layers.composed.repeated import RepeatedLayer
from tqec.compile.graph import TopologicalComputationGraph
from tqec.compile.specs.library.generators.memory import (
get_memory_horizontal_boundary_plaquettes, …
```
> Use `default_value` instead of `default_factory` in `FrozenDefaultDict`; close #534

- src/tqec/simulation/__init__.py
- src/tqec/simulation/simulation.py
- src/tqec/simulation/split.py
Fixes #364.
The solution is mainly based on [my previous comments](https://github.com/tqec/tqec/issues/364#issuecomment-2574720834).
For the `custom_error_key` used in `sinter`, I use the following heuristic algorithm, copied from the docstring of `heuristic_custom_error_key`.
```txt
Currently, we determine the most likely observable error combinations by
analyzing their correlation surfaces. For each combination, we perform an
AND on the corresponding correlation surfaces and calculate the area of the
resulting span. We then rank these combinations according to the computed
AND-area metric. To derive a reasonable error metric, we select
``ordered_combs[-len(observables)]`` for two reasons: first, errors should
be easy to sample so as not to require excessive shots; and second, once an …
```
> Single simulation run for multiple observable statistics

- docs/contributor_guide.rst
This PR adds more details on the use of the `-e` option when installing `tqec` for contributors.
> Add explanations for `-e` option to `pip` when installing

- src/tqec/compile/specs/library/generators/spatial_test.py
- src/tqec/templates/qubit.py
- src/tqec/templates/qubit_test.py
This PR removes a warning that was not up-to-date when instantiating `QubitSpatialCubeTemplate`.
> Removing warning when instantiating QubitSpatialCubeTemplate with k=1

- src/tqec/compile/compile.py
- src/tqec/computation/block_graph.py
- src/tqec/computation/block_graph_test.py
- src/tqec/computation/pipe.py
- src/tqec/computation/pipe_test.py
- src/tqec/interop/collada/read_write.py
- src/tqec/interop/collada/read_write_test.py
- src/tqec/utils/position.py
Fixes #536.
This PR includes the following changes:
- Do not check colors of shadowed faces when validating the block graph
- Do not fix shadowed faces when importing dae file or rotate block graph, leave it to compilation pipeline
- Add `validate` and `fix_shadowed_faces` at the start of compilation pipeline
> Properly handle shadowed faces

- src/tqec/computation/block_graph.py
- src/tqec/computation/block_graph_test.py
- src/tqec/gallery/cnot_test.py
- src/tqec/gallery/cz_test.py
- src/tqec/gallery/move_rotation_test.py
- src/tqec/gallery/three_cnots_test.py
The definition of "spacetime volume" used throughout Austin's lectures is "the number of non-port cubes the computation has". 
Previously, it was defined as "the size of the bounding box of the block graph":
https://github.com/tqec/tqec/blob/06420e1b53f227c2f1b6bcb18524f1e41a3c7d03/src/tqec/computation/block_graph.py#L113-L119
This PR renames it as `bounding_box_size` and add the method `spacetime_volume` with the correct definition.
> Correct space time volume definition

- src/tqec/compile/blocks/block.py
- src/tqec/compile/blocks/block_test.py
- src/tqec/compile/blocks/layers/atomic/base.py
- src/tqec/compile/blocks/layers/atomic/layout.py
- src/tqec/compile/blocks/layers/atomic/plaquettes.py
- src/tqec/compile/blocks/layers/atomic/plaquettes_test.py
- src/tqec/compile/blocks/layers/atomic/raw.py
- src/tqec/compile/blocks/layers/composed/base.py
- src/tqec/compile/blocks/layers/composed/repeated.py
- src/tqec/compile/blocks/layers/composed/sequenced.py
- src/tqec/compile/blocks/layers/composed/sequenced_test.py
- src/tqec/compile/blocks/layers/merge_test.py
- src/tqec/compile/blocks/layers/spatial.py
- src/tqec/compile/blocks/layers/temporal.py
- src/tqec/compile/blocks/positioning.py
- src/tqec/compile/graph.py
- src/tqec/compile/graph_test.py
- src/tqec/templates/enums.py
- src/tqec/utils/position.py
This PR fixes #539.
Note that the second issue was solved by simply delaying the "same `scalable_shape`" check to when `SequencedLayers.scalable_shape` is called, which is fine for the moment because we never call that property after merging the layers, and the only supported way to get a `LayoutLayer` is by merging the layers.
> Fix layer approach

- src/tqec/compile/tree/tree.py
- src/tqec/plaquette/compilation/base.py
- src/tqec/plaquette/debug.py
- src/tqec/plaquette/plaquette.py
- src/tqec/plaquette/rpng/translators/default.py
One of the challenge we often face when implementing new plaquettes/features in `tqec` is due to wrong schedules, leading to error when creating the quantum circuit (two gates touching the same qubit at the same time).
These errors are very tedious to debug.
This PR introduces an optional field in `Plaquette` that includes debug information (for the moment, only the RPNG used to create the plaquette, but this can be improved later if the need arise).
The code introduced also allows to plot a `LayerTree` as a collection of `.svg` files. For example, the following code
```py
from pathlib import Path
from tqec.compile.blocks.block import Block
from tqec.compile.blocks.layers.atomic.plaquettes import PlaquetteLayer
from tqec.compile.blocks.layers.composed.repeated import RepeatedLayer
from …
```
> Add debug information to `Plaquette`

- benchmarks/cnot_all_observables.py
This fixes issue #566.
The code now runs. The output looks plausible. It is difficult to confirm that it is the same as that output by the old compile pipeline as there have been several commits since the deprecated compile script was deleted. 
My changes to the script are minimal. I have replaced the default arguments of CSS_BLOCK_BUILDER and CSS_SUBSTITUTION_BUILDER in compile_block_graph(), with the new default parameter of FIXED_BULK_CONVENTION in the new compile_block_graph function. It would be good if someone more familiar with the new pipeline could confirm that the new default parameters are intended to produce the same result as the old default parameters.
> Fix cnot_all_observables.py

- src/tqec/computation/block_graph.py
- src/tqec/computation/block_graph_test.py
See issue #527 (there will be a second PR for `fill_ports` but need to have `relabel_cubes` solved first)
Relabel cubes searching the cubes by `position` or by `label` (allows to relabel a group of cubes). It raises an exception if the name given is been used in an existing port. I've tested it with:
```
from tqec import BlockGraph, Position3D
def main():    
block_graph = BlockGraph.from_dae_file("slide67_open.dae")
print(f"Cubes:")
for cube in block_graph.cubes:
print(cube, cube.label)
block_graph.relabel_cubes(Position3D(-1,0,0), "PortNew1")
print(f"New Cubes:")
for cube in block_graph.cubes:
print(cube, cube.label)
block_graph.relabel_cubes("Port1", "PortNew2")
print(f"Cubes:")
for cube in block_graph.cubes:
print(cube, cube.label)
block_graph.view_as_html("open_ports.html")
if …
```
> Introduce BlockGraph.relabel_cubes

- assets/tqec_blockgraph_loader.rb
Instructions to use the extension:
1. With the template.skp opened in SketchUp, save each element as a component. They are going to be saved as zxx.skp, zxz.skp, etc. in Components folder (save the pathname of that folder to use it in the next step).
2. In line `COMPONENT_FOLDER  ||=` replace the text with the pathname to the `Components` folder in SketchUp.
3. Save the `tqec_blockgraph_loader.rb` in the `Plugins` folder of SketchUp.
4. Now you can import a JSON file with the blockgraph and the component's name won't be lost. It's possible to export the estructure created in SketchUp as a DAE file and re-import it in TQEC.
> First version of SketchUp extension to import JSON files

- .github/workflows/ci.yml
- pyproject.toml
This PR adds the option to show which lines are not covered by unit tests. I noticed two modules are missing proper unit test coverage, but there wasn't enough information. 
This PR adds the option to show such lines. 
https://github.com/tqec/tqec/actions/runs/15336433395/job/43154562414?pr=593#step:6:167
> Add option to show lines missing unit test coverage

- src/tqec/compile/detectors/database.py
This PR makes DetectorDatabase reading and writing more robust and extensible. 
It should fix #653, even if it seems like an error that does not come from TQEC itself.
> Improve detector database IO

- README.md
- docs/index.rst
- docs/legal_notice.rst
Adds badges to the readme to provide quick access to things a person new to tqec might be interested in.
> Add github badges to readme

- src/tqec/compile/specs/library/generators/fixed_boundary.py
A quick fix to the description of one of the functions for the spatial horizontal hadamard. The function was behaving correctly, but the description confusingly didn't match. 
I thought it was clearer to push this separately, rather than wrap it into my more complicated push implementing the other spatial hadamard situations.
> fix description
